// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXRPGT3j6u810Mf1KqgVNofRASyStYlm4',
    appId: '1:558122983964:web:56979d1e8328b9cf3375d9',
    messagingSenderId: '558122983964',
    projectId: 'chatwave-12',
    authDomain: 'chatwave-12.firebaseapp.com',
    storageBucket: 'chatwave-12.appspot.com',
    measurementId: 'G-96DYN9R6PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHGDiKCz2VcgUxCoRIELTdbR6bR-bF8q0',
    appId: '1:558122983964:android:b920854995b989f53375d9',
    messagingSenderId: '558122983964',
    projectId: 'chatwave-12',
    storageBucket: 'chatwave-12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdSDRcE0ttoz-BOn9KMvpSK3jJwhYFfIs',
    appId: '1:558122983964:ios:9a5e94124c65c4233375d9',
    messagingSenderId: '558122983964',
    projectId: 'chatwave-12',
    storageBucket: 'chatwave-12.appspot.com',
    iosBundleId: 'com.example.chatwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdSDRcE0ttoz-BOn9KMvpSK3jJwhYFfIs',
    appId: '1:558122983964:ios:ed97efc9c29b1fec3375d9',
    messagingSenderId: '558122983964',
    projectId: 'chatwave-12',
    storageBucket: 'chatwave-12.appspot.com',
    iosBundleId: 'com.example.chatwave.RunnerTests',
  );
}
